apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "postgres-chart.fullname" . }}-init-{{ .Release.Revision }}
  labels:
    {{- include "postgres-chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "postgres-chart.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
      - name: db-init
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: PGPASSWORD
          value: {{ .Values.postgres.password | quote }}
        command: ["bash", "-c", "/init-databases.sh"]
        volumeMounts:
        - name: init-script
          mountPath: /init-databases.sh
          subPath: init-databases.sh
          readOnly: true
      volumes:
      - name: init-script
        configMap:
          name: {{ include "postgres-chart.fullname" . }}-init-script
          defaultMode: 0755

