# Default values for postgres-chart

fullnameOverride: postgres

replicaCount: 1

image:
  repository: library/postgres
  pullPolicy: IfNotPresent
  tag: "13"

postgres:
  user: program
  password: test
  database: postgres

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  size: 8Gi
  storageClass: ""

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

