fullnameOverride: gateway-service

image:
  repository: ""  # Will be set in CI/CD
  tag: "latest"
  pullPolicy: Always

service:
  port: 8080

env:
  - name: CARS_SERVICE_URL
    value: "http://cars-service:8070"
  - name: RENTAL_SERVICE_URL
    value: "http://rental-service:8060"
  - name: PAYMENT_SERVICE_URL
    value: "http://payment-service:8050"
  - name: OIDC_ISSUER
    value: "https://dev-x72evwvlbitajlk0.us.auth0.com/"
  - name: OIDC_AUDIENCE
    value: "https://dev-x72evwvlbitajlk0.us.auth0.com/api/v2/"
  - name: OIDC_CLIENT_ID
    value: "pqn53cnXeQEFQW7xk5RHc0NsbRP6cEeQ"
  - name: OIDC_CLIENT_SECRET
    value: "KGMAve77s3mF2oT8XBznOMnUELvc23FNjT4iLk3N3JJzISLe85jq8R9iG9u84gBw"
  - name: OIDC_TOKEN_URL
    value: "https://dev-x72evwvlbitajlk0.us.auth0.com/oauth/token"
  - name: OIDC_WELL_KNOWN_URL
    value: "https://dev-x72evwvlbitajlk0.us.auth0.com/.well-known/openid-configuration"
  - name: OIDC_JWKS_URL
    value: "https://dev-x72evwvlbitajlk0.us.auth0.com/.well-known/jwks.json"
  - name: OIDC_SCOPE
    value: "openid profile email"

command:
  - uvicorn
  - services.gateway_service.main:app
  - --host
  - 0.0.0.0
  - --port
  - "8080"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: ""  # Will be set based on cluster ingress
      paths:
        - path: /
          pathType: Prefix

