fullnameOverride: rental-service

image:
  repository: ""  # Will be set in CI/CD
  tag: "latest"
  pullPolicy: Always

service:
  port: 8060

env:
  - name: DATABASE_URL
    value: "postgresql://program:test@postgres:5432/rentals"
  - name: OIDC_ISSUER
    value: "http://localhost:8080"
  - name: OIDC_AUDIENCE
    value: "rsoi-lab5-ci"
  - name: OIDC_CLIENT_ID
    value: "rsoi-lab5-ci"
  - name: OIDC_CLIENT_SECRET
    value: "rsoi-lab5-ci-secret"
  - name: OIDC_TOKEN_URL
    value: "http://gateway-service:8080/oauth/token"
  - name: OIDC_JWKS
    value: '{"keys":[{"kty":"oct","kid":"local-ci","k":"cnNvaS1sYWI1LWNpLXNlY3JldA"}]}'
  - name: OIDC_SCOPE
    value: "openid profile email"


command:
  - uvicorn
  - services.rental_service.main:app
  - --host
  - 0.0.0.0
  - --port
  - "8060"

