fullnameOverride: ui-service

image:
  repository: ""
  tag: "latest"
  pullPolicy: Always

service:
  port: 3000

env:
  - name: UI_API_BASE_URL
    value: "http://localhost:8080"
  - name: UI_IDENTITY_URL
    value: "http://localhost:8080"
  - name: OIDC_CLIENT_ID
    value: "rsoi-lab5-ci"
  - name: OIDC_REDIRECT_URI
    value: "http://localhost:3000/callback"

command:
  - uvicorn
  - services.ui_service.main:app
  - --host
  - 0.0.0.0
  - --port
  - "3000"

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix

